language: node_js

node_js:
  - 10

os:
  - linux
  - osx

env:
  - NODE_ENV=production

before_install:
  - npm install --global esy@latest
  - bash -e ci/travis_before_install.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET_NAME=darwin-x64; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET_NAME=linux-x64; fi

cache:
  timeout: 360
  yarn: true
  directories:
    - '$HOME/.esy/'
    - '$HOME/.npm/'
    - 'node_modules/'
    - 'test/node_modules/'

install:
  - esy install
  - cd test && yarn install && cd ..

script:
  - esy build
  - esy test
#  - mv _build/default/graphql_to_reason.exe graphql_ppx-$TARGET_NAME.exe

