language: node_js

node_js:
  - 10

os:
  - linux
  - osx

sudo: required

services:
  - docker

before_install:
  - npm install --global esy@latest
  - esy install
  - cd tests && yarn install

script:
  - esy build
  - NODE_ENV=production make test
#  - mv _build/default/graphql_to_reason.exe graphql_ppx-$TARGET_NAME.exe

