language: node_js

node_js:
  - 10

os:
  - linux
  - osx

sudo: required

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.esy
    - test/node_modules

before_install:
  - npm install --global esy@latest
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - esy install
  - cd tests && yarn install && cd ..

script:
  - esy build
  - esy test
#  - mv _build/default/graphql_to_reason.exe graphql_ppx-$TARGET_NAME.exe

