// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var User = 0;

var Basic = 0;

var Swapi = 0;

var Extend = 0;

var Github = 0;

var Scalar = 0;

var Sketchsh = 0;

var Directives = 0;

exports.User = User;
exports.Basic = Basic;
exports.Swapi = Swapi;
exports.Extend = Extend;
exports.Github = Github;
exports.Scalar = Scalar;
exports.Sketchsh = Sketchsh;
exports.Directives = Directives;
/* No side effect */
